version: '3'
services:
  operation:
    build: ./docker
    container_name: operation
    working_dir: /code
    tty: true
    volumes:
      - ./code:/code
      - ./resources:/resources
    environment:
      PYTHONPATH: /code
    env_file:
      - .env
  mariadb:
    image: mariadb:10.9.4
    container_name: mariadb
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - .env